# Generated by Django 4.2.2 on 2023-06-30 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='category_name_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Наименование категории'),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='category_name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Наименование категории'),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='news_content_kk',
            field=models.TextField(null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='news_content_ru',
            field=models.TextField(null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='news_is_achivment',
            field=models.BooleanField(default=False, verbose_name='Достижение'),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='news_title_kk',
            field=models.CharField(max_length=150, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='news_title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
