# Generated by Django 4.2.2 on 2023-06-16 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CyclicMCModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmc_name', models.CharField(max_length=200, verbose_name='Цикловая метод. комиссия')),
            ],
            options={
                'verbose_name': 'Цикловая методическая комиссия',
                'verbose_name_plural': 'Цикловая методическая комиссия',
            },
        ),
        migrations.CreateModel(
            name='JobTitleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=200, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Список должностей',
                'verbose_name_plural': 'Список должностей',
            },
        ),
        migrations.CreateModel(
            name='StaffMemberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('foto', models.ImageField(blank=True, upload_to='upload/staff', verbose_name='Фото')),
                ('info', models.TextField(verbose_name='Информация')),
                ('cmc', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='staff.cyclicmcmodel', verbose_name='Цикловая комиссия')),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.jobtitlemodel', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Персонал',
                'verbose_name_plural': 'Персонал',
            },
        ),
    ]
