# Generated by Django 4.2.2 on 2023-06-30 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmcELModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('foto', models.ImageField(blank=True, upload_to='upload/staff', verbose_name='Фото')),
                ('info', models.TextField(blank=True, verbose_name='Информация')),
                ('info_ru', models.TextField(blank=True, null=True, verbose_name='Информация')),
                ('info_kk', models.TextField(blank=True, null=True, verbose_name='Информация')),
                ('is_working', models.BooleanField(default=False, verbose_name='Статус работы')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'ЦМК электротехнических и экономических дисциплин',
                'verbose_name_plural': 'ЦМК электротехнических и экономических дисциплин',
            },
        ),
        migrations.CreateModel(
            name='CmcFIZModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('foto', models.ImageField(blank=True, upload_to='upload/staff', verbose_name='Фото')),
                ('info', models.TextField(blank=True, verbose_name='Информация')),
                ('info_ru', models.TextField(blank=True, null=True, verbose_name='Информация')),
                ('info_kk', models.TextField(blank=True, null=True, verbose_name='Информация')),
                ('is_working', models.BooleanField(default=False, verbose_name='Статус работы')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'ЦМК физической культуры и НВП',
                'verbose_name_plural': 'ЦМК физической культуры и НВП',
            },
        ),
        migrations.CreateModel(
            name='CmcITModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('foto', models.ImageField(blank=True, upload_to='upload/staff', verbose_name='Фото')),
                ('info', models.TextField(blank=True, verbose_name='Информация')),
                ('info_ru', models.TextField(blank=True, null=True, verbose_name='Информация')),
                ('info_kk', models.TextField(blank=True, null=True, verbose_name='Информация')),
                ('is_working', models.BooleanField(default=False, verbose_name='Статус работы')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'ЦМК информационных дисциплин',
                'verbose_name_plural': 'ЦМК информационных дисциплин',
            },
        ),
        migrations.CreateModel(
            name='CmcLangModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('foto', models.ImageField(blank=True, upload_to='upload/staff', verbose_name='Фото')),
                ('info', models.TextField(blank=True, verbose_name='Информация')),
                ('info_ru', models.TextField(blank=True, null=True, verbose_name='Информация')),
                ('info_kk', models.TextField(blank=True, null=True, verbose_name='Информация')),
                ('is_working', models.BooleanField(default=False, verbose_name='Статус работы')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'ЦМК языковых дисциплин',
                'verbose_name_plural': 'ЦМК языковых дисциплин',
            },
        ),
        migrations.CreateModel(
            name='CmcOBModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('foto', models.ImageField(blank=True, upload_to='upload/staff', verbose_name='Фото')),
                ('info', models.TextField(blank=True, verbose_name='Информация')),
                ('info_ru', models.TextField(blank=True, null=True, verbose_name='Информация')),
                ('info_kk', models.TextField(blank=True, null=True, verbose_name='Информация')),
                ('is_working', models.BooleanField(default=False, verbose_name='Статус работы')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'ЦМК общеодразовательных дисциплин',
                'verbose_name_plural': 'ЦМК общеодразовательных дисциплин',
            },
        ),
        migrations.CreateModel(
            name='DepDirectorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('foto', models.ImageField(blank=True, upload_to='upload/staff', verbose_name='Фото')),
                ('info', models.TextField(blank=True, verbose_name='Информация')),
                ('info_ru', models.TextField(blank=True, null=True, verbose_name='Информация')),
                ('info_kk', models.TextField(blank=True, null=True, verbose_name='Информация')),
                ('is_working', models.BooleanField(default=False, verbose_name='Статус работы')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Заместители директора',
                'verbose_name_plural': 'Заместители директора',
            },
        ),
        migrations.CreateModel(
            name='DepHeadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('foto', models.ImageField(blank=True, upload_to='upload/staff', verbose_name='Фото')),
                ('info', models.TextField(blank=True, verbose_name='Информация')),
                ('info_ru', models.TextField(blank=True, null=True, verbose_name='Информация')),
                ('info_kk', models.TextField(blank=True, null=True, verbose_name='Информация')),
                ('is_working', models.BooleanField(default=False, verbose_name='Статус работы')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Заведующий отделением',
                'verbose_name_plural': 'Заведующий отделением',
            },
        ),
        migrations.CreateModel(
            name='DirectorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('foto', models.ImageField(blank=True, upload_to='upload/staff', verbose_name='Фото')),
                ('info', models.TextField(blank=True, verbose_name='Информация')),
                ('info_ru', models.TextField(blank=True, null=True, verbose_name='Информация')),
                ('info_kk', models.TextField(blank=True, null=True, verbose_name='Информация')),
                ('is_working', models.BooleanField(default=False, verbose_name='Статус работы')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Директор',
                'verbose_name_plural': 'Директор',
            },
        ),
        migrations.CreateModel(
            name='PositionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=200, verbose_name='Должность')),
                ('position_name_ru', models.CharField(max_length=200, null=True, verbose_name='Должность')),
                ('position_name_kk', models.CharField(max_length=200, null=True, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Справочник должностей',
                'verbose_name_plural': 'Справочник должностей',
            },
        ),
        migrations.RemoveField(
            model_name='staffmembermodel',
            name='cmc',
        ),
        migrations.RemoveField(
            model_name='staffmembermodel',
            name='job_title',
        ),
        migrations.DeleteModel(
            name='CyclicMCModel',
        ),
        migrations.DeleteModel(
            name='JobTitleModel',
        ),
        migrations.DeleteModel(
            name='StaffMemberModel',
        ),
        migrations.AddField(
            model_name='directormodel',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.positionmodel', verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='depheadmodel',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.positionmodel', verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='depdirectormodel',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.positionmodel', verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='cmcobmodel',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.positionmodel', verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='cmclangmodel',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.positionmodel', verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='cmcitmodel',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.positionmodel', verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='cmcfizmodel',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.positionmodel', verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='cmcelmodel',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.positionmodel', verbose_name='Должность'),
        ),
    ]
