# Generated by Django 4.2.2 on 2023-06-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(max_length=300, verbose_name='Адрес')),
                ('e_mail', models.CharField(max_length=20, verbose_name='e-mail')),
                ('tel', models.CharField(max_length=20, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='CollegeHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField(verbose_name='Дата события')),
                ('info', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'История колледжа',
                'verbose_name_plural': 'История колледжа',
            },
        ),
    ]
