# Generated by Django 4.2.2 on 2023-09-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_collegepartnersmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeDocsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_license', models.FileField(upload_to='uploads/Docs', verbose_name='Лицензия')),
                ('college_reg', models.FileField(upload_to='uploads/Docs', verbose_name='Устав')),
            ],
            options={
                'verbose_name': 'Документы колледжа',
                'verbose_name_plural': 'Документы колледжа',
            },
        ),
    ]
