# Generated by Django 4.2.2 on 2023-06-30 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specinfomodel',
            name='spec_info_kk',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='specinfomodel',
            name='spec_info_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='specinfomodel',
            name='spec_name_kk',
            field=models.CharField(max_length=200, null=True, verbose_name='Специальность'),
        ),
        migrations.AddField(
            model_name='specinfomodel',
            name='spec_name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Специальность'),
        ),
    ]
