# Generated by Django 4.1.7 on 2023-02-14 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=100, verbose_name='Наименование должности')),
            ],
            options={
                'verbose_name': 'Должности',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='WorkerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('post_level', models.CharField(choices=[('0', 'Руководитель'), ('1', 'Заместитель руководителя'), ('2', 'Заведующий отделением'), ('3', 'Преподаватель')], max_length=1, verbose_name='Уровень')),
                ('foto', models.ImageField(upload_to='uploads/workers/foto', verbose_name='Фото')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('info', models.TextField(verbose_name='Информация')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.postmodel', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудники',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
